global:
  # Default is every 1 minute.
  scrape_interval:     15s 
  
  # Evaluate rules every 5 seconds. The default is every 1 minute.
  evaluation_interval: 30s 

rule_files:
# - "first_rules.yml"
# - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  - job_name: 'scrape_prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']

  - job_name: 'scrape_gateway_service'
    metrics_path: '/actuator/prometheus'
    #scrape_interval: 15s
    static_configs:
    # refer system ip address rather that localhost / host.docker.internal for  docker container     
      - targets: ['host.docker.internal:8181'] 
        labels:
          # application: "Gateway Service"
          
          
     
          
          
          
       