version: '3'

services:

  #------------------------------------------
  #--- SERVICES -----------------------------
  #------------------------------------------
               
  # app auth service
  app_auth:
    container_name: auth_service
    image: denitiawan/springboot-microservices-auth-service:latest
    environment:           
      SMP_AUTH_HOST: 'auth_service'
      SMP_AUTH_PORT: 8282

      SMP_AUTH_DB_HOST: 'host.docker.internal'
      SMP_AUTH_DB_PORT: 3310
      SMP_AUTH_DB_USER: 'user'
      SMP_AUTH_DB_PASSWORD: 'password'
      SMP_AUTH_DB_NAME: 'db_auth'     
      
      SMP_REDIS_HOST: 'host.docker.internal'
      SMP_REDIS_PORT: 6379    
      SMP_REDIS_PASSWORD: 'password123'  
      
      
      SMP_DISCOVERY_HOST_NAME: host.docker.internal
      SMP_DISCOVERY_URL: http://host.docker.internal:8761/eureka
      
      SMP_CORS_MICROSERVICES_ALLOW_ORIGIN: 'http://localhost:8181'
      
    ports:      
      - '8282:8282'
    expose:      
      - '8282'      
    networks:
      
      - network
      
    depends_on:      
      - app_discovery
      
    mem_limit: 256m
    mem_reservation: 128M
    cpus: 0.1  
      
  # app master service
  app_master:
    container_name: master_service
    image: denitiawan/springboot-microservices-master-service:latest
    environment:           
      SMP_MST_HOST: 'master_service'
      SMP_MST_PORT: 8383

      SMP_MST_DB_HOST: 'host.docker.internal'
      SMP_MST_DB_PORT: 3311
      SMP_MST_DB_USER: 'user'
      SMP_MST_DB_PASSWORD: 'password'
      SMP_MST_DB_NAME: 'db_master'    

      SMP_RABBITMQ_HOST: 'host.docker.internal'
      SMP_RABBITMQ_PORT: 5672
      SMP_RABBITMQ_USERNAME: guest
      SMP_RABBITMQ_PASSWORD: guest   

      
      SMP_DISCOVERY_HOST_NAME: host.docker.internal
      SMP_DISCOVERY_URL: http://host.docker.internal:8761/eureka     

      SMP_CORS_MICROSERVICES_ALLOW_ORIGIN: 'http://localhost:8181'      
      
    ports:      
      - '8383:8383'
    expose:      
      - '8383'      
    networks:
       
      - network
      
    depends_on:      
      - app_discovery
      
    mem_limit: 256m
    mem_reservation: 128M
    cpus: 0.1  
      
      
  # app transaction service
  app_trans:
    container_name: trans_service
    image: denitiawan/springboot-microservices-trans-service:latest
    environment:           
      SMP_TRS_HOST: 'trans_service'
      SMP_TRS_PORT: 8484

      SMP_TRS_DB_HOST: 'host.docker.internal'
      SMP_TRS_DB_PORT: 3312
      SMP_TRS_DB_USER: 'user'
      SMP_TRS_DB_PASSWORD: 'password'
      SMP_TRS_DB_NAME: 'db_transaction'     
      
      
      SMP_RABBITMQ_HOST: 'host.docker.internal'
      SMP_RABBITMQ_PORT: 5672
      SMP_RABBITMQ_USERNAME: guest
      SMP_RABBITMQ_PASSWORD: guest
      
      
      
      SMP_DISCOVERY_HOST_NAME: host.docker.internal
      SMP_DISCOVERY_URL: http://host.docker.internal:8761/eureka
      
      SMP_CORS_MICROSERVICES_ALLOW_ORIGIN: 'http://localhost:8181'
      
    ports:      
      - '8484:8484'
    expose:      
      - '8484'      
    networks:
      
      - network
      
    depends_on:      
      - app_discovery
      
    mem_limit: 256m
    mem_reservation: 128M
    cpus: 0.1  
      
       
  # app inventory service
  app_inventory:
    container_name: inventory_service
    image: denitiawan/springboot-microservices-inventory-service:latest
    environment:           
      SMP_INV_HOST: 'inventory_service'
      SMP_INV_PORT: 8585

      SMP_INV_DB_HOST: 'host.docker.internal'
      SMP_INV_DB_PORT: 3313
      SMP_INV_DB_USER: 'user'
      SMP_INV_DB_PASSWORD: 'password'
      SMP_INV_DB_NAME: 'db_inventory'     
      
      
      SMP_DISCOVERY_HOST_NAME: host.docker.internal
      SMP_DISCOVERY_URL: http://host.docker.internal:8761/eureka
      
      SMP_CORS_MICROSERVICES_ALLOW_ORIGIN: 'http://localhost:8181'
      
    ports:      
      - '8585:8585'
    expose:      
      - '8585'      
    networks:
      
      - network
      
    depends_on:      
      - app_discovery
    
    mem_limit: 256m
    mem_reservation: 128M
    cpus: 0.1  
      
           
  # app schmaster service
  app_schmaster:
    container_name: schmaster_service
    image: denitiawan/springboot-microservices-schmaster-service:latest
    environment:           
      SMP_SCHMST_HOST: 'schmaster_service'
      SMP_SCHMST_PORT: 8686

      SMP_ELASTIC_HOST: 'host.docker.internal'
      SMP_ELASTIC_PORT: 9200
      SMP_ELASTIC_USER: 'user'
      SMP_ELASTIC_PASSWORD: 'password'      
            
      SMP_RABBITMQ_HOST: 'host.docker.internal'
      SMP_RABBITMQ_PORT: 5672
      SMP_RABBITMQ_USERNAME: guest
      SMP_RABBITMQ_PASSWORD: guest
      
      
      SMP_DISCOVERY_HOST_NAME: host.docker.internal
      SMP_DISCOVERY_URL: http://host.docker.internal:8761/eureka
      
      SMP_CORS_MICROSERVICES_ALLOW_ORIGIN: 'http://localhost:8181'
      
    ports:      
      - '8686:8686'
    expose:      
      - '8686'      
    networks:
      
      - network
      
    depends_on:      
      - app_discovery
      
    mem_limit: 256m
    mem_reservation: 128M
    cpus: 0.1  



  # app schtransaction service (pod 1)
  app_schtransaction:
    container_name: schtransaction_service
    image: denitiawan/springboot-microservices-schtransaction-service:latest
    environment:           
      SMP_SCHTRS_HOST: 'schtransaction_service'
      SMP_SCHTRS_PORT: 8787

      SMP_ELASTIC_HOST: 'host.docker.internal'
      SMP_ELASTIC_PORT: 9200
      SMP_ELASTIC_USER: 'user'
      SMP_ELASTIC_PASSWORD: 'password'      
      
      
      SMP_RABBITMQ_HOST: 'host.docker.internal'
      SMP_RABBITMQ_PORT: 5672
      SMP_RABBITMQ_USERNAME: guest
      SMP_RABBITMQ_PASSWORD: guest
      
      
      SMP_DISCOVERY_HOST_NAME: host.docker.internal
      SMP_DISCOVERY_URL: http://host.docker.internal:8761/eureka
      
      SMP_CORS_MICROSERVICES_ALLOW_ORIGIN: 'http://localhost:8181'
      
    ports:      
      - '8787:8787'
    expose:      
      - '8787'      
    networks:
      
      - network
      
    depends_on:      
      - app_discovery
    
    mem_limit: 256m
    mem_reservation: 128M
    cpus: 0.1  
      
   

      
      
  # app report service
  app_report:
    container_name: report_service
    image: denitiawan/springboot-microservices-report-service:latest
    environment:           
      SMP_REPORT_HOST: 'report_service'
      SMP_REPORT_PORT: 8888

      SMP_REPORT_DB_HOST: 'host.docker.internal'
      SMP_REPORT_DB_PORT: 3314
      SMP_REPORT_DB_USER: 'user'
      SMP_REPORT_DB_PASSWORD: 'password'
      SMP_REPORT_DB_NAME: 'db_report'     
      
      
      SMP_RABBITMQ_HOST: 'host.docker.internal'
      SMP_RABBITMQ_PORT: 5672
      SMP_RABBITMQ_USERNAME: guest
      SMP_RABBITMQ_PASSWORD: guest
      
      
      SMP_DISCOVERY_HOST_NAME: host.docker.internal
      SMP_DISCOVERY_URL: http://host.docker.internal:8761/eureka
      
      SMP_CORS_MICROSERVICES_ALLOW_ORIGIN: 'http://localhost:8181'
      
    ports:      
      - '8888:8888'
    expose:      
      - '8888'      
    networks:
      
      - network
      
    depends_on:      
      - app_discovery      
      
    mem_limit: 256m
    mem_reservation: 128M
    cpus: 0.1  
      
        
      
  # app email service
  app_email:
    container_name: email_service
    image: denitiawan/springboot-microservices-email-service:latest
    environment:           
      SMP_EMAIL_HOST: 'email_service'
      SMP_EMAIL_PORT: 8989
               
      SMP_RABBITMQ_HOST: 'host.docker.internal'
      SMP_RABBITMQ_PORT: 5672
      SMP_RABBITMQ_USERNAME: guest
      SMP_RABBITMQ_PASSWORD: guest  
      
      
      SMP_DISCOVERY_HOST_NAME: host.docker.internal
      SMP_DISCOVERY_URL: http://host.docker.internal:8761/eureka
      
      SMP_CORS_MICROSERVICES_ALLOW_ORIGIN: 'http://localhost:8181'
      
    ports:      
      - '8989:8989'
    expose:      
      - '8989'      
    networks:
      
      - network
      
    depends_on:     
      - app_discovery
    
    mem_limit: 256m
    mem_reservation: 128M
    cpus: 0.1  
         
         
  #------------------------------------------
  #-- GATEWAY -------------------------------
  #------------------------------------------      
      
  # app api gateway service
  app_gateway:
    container_name: gateway_service
    image: denitiawan/springboot-microservices-gateway-service:latest
    environment:           
      SMP_GW_HOST: 'gateway_service'
      SMP_GW_PORT: 8181

      SMP_REDIS_HOST: 'host.docker.internal'
      SMP_REDIS_PORT: 6379    
      SMP_REDIS_PASSWORD: 'password123'                        
      
      SMP_GW_ROUTING_SERVER_URL_AUTH: 'http://host.docker.internal:8282'
      SMP_GW_ROUTING_SERVER_URL_MASTER: 'http://host.docker.internal:8383'
      SMP_GW_ROUTING_SERVER_URL_TRANSACTION: 'http://host.docker.internal:8484'
      SMP_GW_ROUTING_SERVER_URL_INVENTORY: 'http://host.docker.internal:8585'
      SMP_GW_ROUTING_SERVER_URL_SCHMASTER: 'http://host.docker.internal:8686'
      SMP_GW_ROUTING_SERVER_URL_SCHTRANSACTION: 'host.docker.internal:8787'
      SMP_GW_ROUTING_SERVER_URL_REPORT: 'http://host.docker.internal:8888'
      SMP_GW_ROUTING_SERVER_URL_EMAIL: 'http://host.docker.internal:8989'              
      
      SMP_DISCOVERY_HOST_NAME: host.docker.internal
      SMP_DISCOVERY_URL: http://host.docker.internal:8761/eureka
            
      SMP_CORS_GATEWAY_ALLOW_ORIGIN_FRONTEND: 'http://localhost:3006'
      SMP_CORS_GATEWAY_ALLOW_ORIGIN_PROMETHEUS: 'http://host.docker.internal:9090'
      
      
      SMP_GW_RATE_LIMMITER_REQUEST_IN_SECOND_MIN: 1
      SMP_GW_RATE_LIMMITER_REQUEST_IN_SECOND_MAX: 3
      
      SMP_GW_CIRCUIT_BREAKER_DURATION_IN_SECOND_MAX: 5
            
      
    ports:      
      - '8181:8181'
    expose:      
      - '8181'      
    networks:
      
      - network
      
    depends_on:    
      - app_email
      - app_report
      - app_schtransaction
      - app_schmaster
      - app_inventory
      - app_trans
      - app_master
      - app_auth            
      - app_discovery       
      
    
      
    mem_limit: 256m
    mem_reservation: 128M
    cpus: 0.1  
      
  # app discovery service
  app_discovery:
    container_name: discovery_service
    image: denitiawan/springboot-microservices-discovery-service:latest
    environment:                 
      SMP_DISCOVERY_PORT: 8761
                    
    ports:      
      - '8761:8761'
    expose:      
      - '8761'      
    networks:
      - network       
 
         
    mem_limit: 256m
    mem_reservation: 128M
    cpus: 0.1 
      
      
      
  #------------------------------------------
  #-- FRONT END -----------------------------
  #------------------------------------------
  
  
  #--- FRONT END ACCEPTED (BY CORS)-------------------
  web:
    container_name: smp_web
    image: denitiawan/springboot-microservices-web:latest-prod
    ports:      
      - 3006:3000       
    networks:
      
      - network
      
    volumes:
      - web_node_modules:/app/node_modules      
    depends_on:
      - app_email
      - app_report
      - app_schtransaction
      - app_schmaster
      - app_inventory
      - app_trans
      - app_master
      - app_auth      
      - app_discovery 
      
    mem_limit: 256m
    mem_reservation: 128M
    cpus: 0.1 
    
  #--- FRONT END BLOCKED (BY CORS)-------------------
  web_3007:
    container_name: smp_web_3007
    image: denitiawan/springboot-microservices-web:latest-prod
    ports:      
      - 3007:3000       
    networks:
      
      - network
      
    volumes:
      - web_node_modules:/app/node_modules      
    depends_on:
      - app_email
      - app_report
      - app_schtransaction
      - app_schmaster
      - app_inventory
      - app_trans
      - app_master
      - app_auth      
      - app_discovery 
      
    mem_limit: 256m
    mem_reservation: 128M
    cpus: 0.1 
    
             
      
networks:
  network:
    driver: bridge
    
    
volumes:
  #prometheus_data: 
  #grafana_data:      
  web_node_modules:  