{
 "title": "Dashboard Springboot Microservice : Counter",
 "description": "Dashboard Springboot Microservice : Counter",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Counter API Gateway", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "200 : SUCCESS",
   "type": "singlestat",
   "description": "the APIs is success ",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{httpStatusCode=\"200\"})"
    }
   ]
  },
  {
   "title": "400 : BAD REQUEST",
   "type": "singlestat",
   "description": "the request body is Invalid argument (invalid request payload)  when access the API ",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{httpStatusCode=\"400\"})"
    }
   ]
  },
  {
   "title": "401 : UNAUTHORIZE",
   "type": "singlestat",
   "description": "the username or password dont have credential for access the application",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{httpStatusCode=\"401\"})"
    }
   ]
  },
  {
   "title": "403 : FORBIDDEN",
   "type": "singlestat",
   "description": "the request token dont have permission for access the API",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{httpStatusCode=\"403\"})"
    }
   ]
  },
  {
   "title": "405 : METHOD NOT ALLOWED",
   "type": "singlestat",
   "description": "CORS : http method is not allowed by backend server",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{httpStatusCode=\"405\"})"
    }
   ]
  },
  {
   "title": "429 : RATE LIMMITER",
   "type": "singlestat",
   "description": "Too Many Request",
   "gridPos": { "h": 4, "w": 4, "x": 19, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{httpStatusCode=\"429\"})"
    }
   ]
  },
  {
   "title": "500 : INTERNAL SERVER ERROR",
   "type": "singlestat",
   "description": "Internal Server Error",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{httpStatusCode=\"500\"})"
    }
   ]
  },
  {
   "title": "503 : CIRCUIT BREAKER",
   "type": "singlestat",
   "description": "Too long wait time out",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{httpStatusCode=\"503\"})"
    }
   ]
  },
  { "title": "Counter Microservices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "AUTH SERVICE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8282\", httpStatusCode=\"200\"})",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8282\", httpStatusCode=\"400\"})",
     "legendFormat": "Bad request"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8282\", httpStatusCode=\"401\"})",
     "legendFormat": "UnAuthorize"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8282\", httpStatusCode=\"403\"})",
     "legendFormat": "Forbidden"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8282\", httpStatusCode=\"405\"})",
     "legendFormat": "Method not allowed"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8282\", httpStatusCode=\"429\"})",
     "legendFormat": "Rate Limmiter"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8282\", httpStatusCode=\"500\"})",
     "legendFormat": "Internal Server Error"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8282\", httpStatusCode=\"503\"})",
     "legendFormat": "Circuit Breaker"
    }
   ]
  },
  {
   "title": "MASTER SERVICE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8383\", httpStatusCode=\"200\"})",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8383\", httpStatusCode=\"400\"})",
     "legendFormat": "Bad request"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8383\", httpStatusCode=\"401\"})",
     "legendFormat": "UnAuthorize"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8383\", httpStatusCode=\"403\"})",
     "legendFormat": "Forbidden"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8383\", httpStatusCode=\"405\"})",
     "legendFormat": "Method not allowed"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8383\", httpStatusCode=\"429\"})",
     "legendFormat": "Rate Limmiter"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8383\", httpStatusCode=\"500\"})",
     "legendFormat": "Internal Server Error"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8383\", httpStatusCode=\"503\"})",
     "legendFormat": "Circuit Breaker"
    }
   ]
  },
  {
   "title": "TRANSACTION SERVICE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8484\", httpStatusCode=\"200\"})",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8484\", httpStatusCode=\"400\"})",
     "legendFormat": "Bad request"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8484\", httpStatusCode=\"401\"})",
     "legendFormat": "UnAuthorize"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8484\", httpStatusCode=\"403\"})",
     "legendFormat": "Forbidden"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8484\", httpStatusCode=\"405\"})",
     "legendFormat": "Method not allowed"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8484\", httpStatusCode=\"429\"})",
     "legendFormat": "Rate Limmiter"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8484\", httpStatusCode=\"500\"})",
     "legendFormat": "Internal Server Error"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8484\", httpStatusCode=\"503\"})",
     "legendFormat": "Circuit Breaker"
    }
   ]
  },
  {
   "title": "INVENTORY SERVICE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8585\", httpStatusCode=\"200\"})",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8585\", httpStatusCode=\"400\"})",
     "legendFormat": "Bad request"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8585\", httpStatusCode=\"401\"})",
     "legendFormat": "UnAuthorize"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8585\", httpStatusCode=\"403\"})",
     "legendFormat": "Forbidden"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8585\", httpStatusCode=\"405\"})",
     "legendFormat": "Method not allowed"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8585\", httpStatusCode=\"429\"})",
     "legendFormat": "Rate Limmiter"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8585\", httpStatusCode=\"500\"})",
     "legendFormat": "Internal Server Error"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8585\", httpStatusCode=\"503\"})",
     "legendFormat": "Circuit Breaker"
    }
   ]
  },
  {
   "title": "SEARCH MASTER SERVICE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8686\", httpStatusCode=\"200\"})",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8686\", httpStatusCode=\"400\"})",
     "legendFormat": "Bad request"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8686\", httpStatusCode=\"401\"})",
     "legendFormat": "UnAuthorize"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8686\", httpStatusCode=\"403\"})",
     "legendFormat": "Forbidden"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8686\", httpStatusCode=\"405\"})",
     "legendFormat": "Method not allowed"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8686\", httpStatusCode=\"429\"})",
     "legendFormat": "Rate Limmiter"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8686\", httpStatusCode=\"500\"})",
     "legendFormat": "Internal Server Error"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8686\", httpStatusCode=\"503\"})",
     "legendFormat": "Circuit Breaker"
    }
   ]
  },
  {
   "title": "SEARCH TRANSACTION SERVICE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8787\", httpStatusCode=\"200\"})",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8787\", httpStatusCode=\"400\"})",
     "legendFormat": "Bad request"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8787\", httpStatusCode=\"401\"})",
     "legendFormat": "UnAuthorize"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8787\", httpStatusCode=\"403\"})",
     "legendFormat": "Forbidden"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8787\", httpStatusCode=\"405\"})",
     "legendFormat": "Method not allowed"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8787\", httpStatusCode=\"429\"})",
     "legendFormat": "Rate Limmiter"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8787\", httpStatusCode=\"500\"})",
     "legendFormat": "Internal Server Error"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8787\", httpStatusCode=\"503\"})",
     "legendFormat": "Circuit Breaker"
    }
   ]
  },
  {
   "title": "REPORT SERVICE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8888\", httpStatusCode=\"200\"})",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8888\", httpStatusCode=\"400\"})",
     "legendFormat": "Bad request"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8888\", httpStatusCode=\"401\"})",
     "legendFormat": "UnAuthorize"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8888\", httpStatusCode=\"403\"})",
     "legendFormat": "Forbidden"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8888\", httpStatusCode=\"405\"})",
     "legendFormat": "Method not allowed"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8888\", httpStatusCode=\"429\"})",
     "legendFormat": "Rate Limmiter"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8888\", httpStatusCode=\"500\"})",
     "legendFormat": "Internal Server Error"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8888\", httpStatusCode=\"503\"})",
     "legendFormat": "Circuit Breaker"
    }
   ]
  },
  {
   "title": "EMAIL SERVICE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8989\", httpStatusCode=\"200\"})",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8989\", httpStatusCode=\"400\"})",
     "legendFormat": "Bad request"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8989\", httpStatusCode=\"401\"})",
     "legendFormat": "UnAuthorize"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8989\", httpStatusCode=\"403\"})",
     "legendFormat": "Forbidden"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8989\", httpStatusCode=\"405\"})",
     "legendFormat": "Method not allowed"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8989\", httpStatusCode=\"429\"})",
     "legendFormat": "Rate Limmiter"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8989\", httpStatusCode=\"500\"})",
     "legendFormat": "Internal Server Error"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8989\", httpStatusCode=\"503\"})",
     "legendFormat": "Circuit Breaker"
    }
   ]
  }
 ]
}