version: '3.5'

services:
 
 
  # jenkins
  jenkins:
    container_name: smp_deployment_jenkins
    image: denitiawan/jenkins-with-docker:1.0
    environment:      
      
      # AUTH-SERVICE
      SMP_AUTH_HOST: 'auth_service'
      SMP_AUTH_PORT: 8282
      SMP_AUTH_DB_HOST: 'host.docker.internal'
      SMP_AUTH_DB_PORT: 3310
      SMP_AUTH_DB_USER: 'user'
      SMP_AUTH_DB_PASSWORD: 'password'
      SMP_AUTH_DB_NAME: 'db_auth'     
    
      # MST-SERVICE
      SMP_MST_HOST: 'master_service'
      SMP_MST_PORT: 8383
      SMP_MST_DB_HOST: 'host.docker.internal'
      SMP_MST_DB_PORT: 3311
      SMP_MST_DB_USER: 'user'
      SMP_MST_DB_PASSWORD: 'password'
      SMP_MST_DB_NAME: 'db_master'    
    
      # TRS-SERVICE
      SMP_TRS_HOST: 'trans_service'
      SMP_TRS_PORT: 8484
      SMP_TRS_DB_HOST: 'host.docker.internal'
      SMP_TRS_DB_PORT: 3312
      SMP_TRS_DB_USER: 'user'
      SMP_TRS_DB_PASSWORD: 'password'
      SMP_TRS_DB_NAME: 'db_transaction'                      
      
      # INV-SERVICE  
      SMP_INV_HOST: 'inventory_service'
      SMP_INV_PORT: 8585
      SMP_INV_DB_HOST: 'host.docker.internal'
      SMP_INV_DB_PORT: 3313
      SMP_INV_DB_USER: 'user'
      SMP_INV_DB_PASSWORD: 'password'
      SMP_INV_DB_NAME: 'db_inventory'                 
      
    
      # SCHMST-SERVICE   
      SMP_SCHMST_HOST: 'schmaster_service'
      SMP_SCHMST_PORT: 8686      
    
      # SCHTRS-SERVICE   
      SMP_SCHTRS_HOST: 'schtransaction_service'
      SMP_SCHTRS_PORT: 8787
                  
      
      # REPORT-SERVICE   
      SMP_REPORT_HOST: 'report_service'
      SMP_REPORT_PORT: 8888
      SMP_REPORT_DB_HOST: 'host.docker.internal'
      SMP_REPORT_DB_PORT: 3314
      SMP_REPORT_DB_USER: 'user'
      SMP_REPORT_DB_PASSWORD: 'password'
      SMP_REPORT_DB_NAME: 'db_report'                           
    
      # EMAIL-SERVICE
      SMP_EMAIL_HOST: 'email_service'
      SMP_EMAIL_PORT: 8989                               

                 
      # GATEWAY
      SMP_GW_HOST: 'gateway_service'
      SMP_GW_PORT: 8181           
      SMP_GW_ROUTING_SERVER_URL_AUTH: 'http://host.docker.internal:8282'
      SMP_GW_ROUTING_SERVER_URL_MASTER: 'http://host.docker.internal:8383'
      SMP_GW_ROUTING_SERVER_URL_TRANSACTION: 'http://host.docker.internal:8484'
      SMP_GW_ROUTING_SERVER_URL_INVENTORY: 'http://host.docker.internal:8585'
      SMP_GW_ROUTING_SERVER_URL_SCHMASTER: 'http://host.docker.internal:8686'
      SMP_GW_ROUTING_SERVER_URL_SCHTRANSACTION: 'host.docker.internal:8787'
      SMP_GW_ROUTING_SERVER_URL_REPORT: 'http://host.docker.internal:8888'
      SMP_GW_ROUTING_SERVER_URL_EMAIL: 'http://host.docker.internal:8989'                    
      SMP_GW_RATE_LIMMITER_REQUEST_IN_SECOND_MIN: 1
      SMP_GW_RATE_LIMMITER_REQUEST_IN_SECOND_MAX: 3      
      SMP_GW_CIRCUIT_BREAKER_DURATION_IN_SECOND_MAX: 5      
      
      # DISCOVERY AS CLIENT     
      SMP_DISCOVERY_HOST_NAME: host.docker.internal
      SMP_DISCOVERY_URL: http://host.docker.internal:8761/eureka     
      
      # CORS ON GATEWAY
      SMP_CORS_GATEWAY_ALLOW_ORIGIN_FRONTEND: 'http://localhost:3006'
      SMP_CORS_GATEWAY_ALLOW_ORIGIN_PROMETHEUS: 'http://host.docker.internal:9090'
      
      # CORS ON SERVICE
      SMP_CORS_MICROSERVICES_ALLOW_ORIGIN: 'http://localhost:8181'
      
      
      # DISCOVERY AS SERVER
      SMP_DISCOVERY_PORT: 8761
      
      
      # ELASTIC
      SMP_ELASTIC_HOST: 'host.docker.internal'
      SMP_ELASTIC_PORT: 9200
      SMP_ELASTIC_USER: 'user'
      SMP_ELASTIC_PASSWORD: 'password'                  
      
      # REDIS
      SMP_REDIS_HOST: 'host.docker.internal'
      SMP_REDIS_PORT: 6379    
      SMP_REDIS_PASSWORD: 'password123'                        
      
      
      # RABBITMQ
      SMP_RABBITMQ_HOST: 'host.docker.internal'
      SMP_RABBITMQ_PORT: 5672
      SMP_RABBITMQ_USERNAME: guest
      SMP_RABBITMQ_PASSWORD: guest
      
                                    
    ports:      
      - '9876:8080'
    expose:      
      - '9876'      
    volumes:
      - jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    
    networks:
      - network
            
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.5      
    


            
  
networks:  
  network:    
    driver: bridge

volumes:               
    jenkins: 
     
 