{
 "title": "Springboot Microservices Project",
 "description": "Springboot Microservices Project",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "API Gateway (Summary)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "TOTAL SUCCESS",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{httpStatusCode=\"200\"})"
    }
   ]
  },
  {
   "title": "TOTAL BAD REQUEST",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{httpStatusCode=\"400\"})"
    }
   ]
  },
  {
   "title": "TOTAL UNAUTHORIZE",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{httpStatusCode=\"401\"})"
    }
   ]
  },
  {
   "title": "TOTAL FORBIDDEN",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{httpStatusCode=\"403\"})"
    }
   ]
  },
  {
   "title": "TOTAL RATE LIMMITER",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{httpStatusCode=\"429\"})"
    }
   ]
  },
  {
   "title": "TOTAL SERVER ERROR",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{httpStatusCode=\"500\"})"
    }
   ]
  },
  {
   "title": "TOTAL CIRCUIT BREAKER",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{httpStatusCode=\"503\"})"
    }
   ]
  },
  { "title": "Auth Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  { "title": "Master Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Transaction Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true
  },
  { "title": "Inventory Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  { "title": "Report Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Email Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true
  }
 ]
}