{
 "title": "Dashboard Springboot Microservices",
 "description": "Resilience4j Spring Cloud Gateway Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "label_values(application)" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(resilience4j_circuitbreaker_state, instance)"
   },
   {
    "name": "circuitbreaker_name",
    "label": "CircuitBreaker Name",
    "query": "label_values(resilience4j_circuitbreaker_state, name)"
   }
  ]
 },
 "panels": [
  { "title": "API Gateway Service (Global)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Success",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{httpStatusCode=\"200\"})"
    }
   ]
  },
  {
   "title": "Circuit Breaker",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{httpStatusCode=\"503\"})"
    }
   ]
  },
  {
   "title": "Rate limmiter (Global)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{httpStatusCode=\"429\"})"
    }
   ]
  },
  {
   "title": "Call duration percentiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "s", "label": "Average duration" }
   ],
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_calls_seconds_count{name=\"CB_MASTER_SERVICES\"}",
     "legendFormat": "90th Percentile"
    },
    {
     "expr": "resilience4j_circuitbreaker_calls_seconds_count{name=\"CB_MASTER_SERVICES\"}",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "resilience4j_circuitbreaker_calls_seconds_count{name=\"CB_MASTER_SERVICES\"}",
     "legendFormat": "98th Percentile"
    },
    {
     "expr": "resilience4j_circuitbreaker_calls_seconds_count{name=\"CB_MASTER_SERVICES\"}",
     "legendFormat": "Median"
    }
   ]
  },
  { "title": "Auth Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Success",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8282\",httpStatusCode=\"200\"})"
    }
   ]
  },
  {
   "title": "Circuit Breaker",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(resilience4j_circuitbreaker_calls_seconds_count{kind=\"failed\",name=\"CB_AUTH_SERVICES\"})"
    }
   ]
  },
  {
   "title": "Rate limmiter ",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8282\",httpStatusCode=\"429\"}"
    }
   ]
  },
  { "title": "Master Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Success",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 35 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8383\",httpStatusCode=\"200\"})"
    }
   ]
  },
  {
   "title": "Circuit Breaker",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 35 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(resilience4j_circuitbreaker_calls_seconds_count{kind=\"failed\",name=\"CB_MASTER_SERVICES\"})"
    }
   ]
  },
  {
   "title": "Rate limmiter ",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 35 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8383\",httpStatusCode=\"429\"}"
    }
   ]
  },
  { "title": "Transaction Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Success",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 47 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8484\",httpStatusCode=\"200\"})"
    }
   ]
  },
  {
   "title": "Circuit Breaker",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 47 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(resilience4j_circuitbreaker_calls_seconds_count{kind=\"failed\",name=\"CB_TRANSACTION_SERVICES\"})"
    }
   ]
  },
  {
   "title": "Rate limmiter ",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 47 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "spring_cloud_gateway_requests_seconds_count{routeUri=\"http://host.docker.internal:8484\",httpStatusCode=\"429\"}"
    }
   ]
  }
 ]
}